### ISSUE TITLE
fillet command throws exception:

### ISSUE THREAD

**Issue by enricofer** [geosim/QAD#1]
fillet command throws exception:
Errore durante l'esecuzione di codice Python:

Traceback (most recent call last):
  File "/Users/enrico/Dropbox/dev/QAD-master/qad_fillet_maptool.py", line 159, in canvasMoveEvent
    self.filletMode, self.transformedRadius, epsg)
  File "/Users/enrico/Dropbox/dev/QAD-master/qad_utils.py", line 8847, in getFilletLinearObjectList
    res = bridgeTheGapBetweenLines(part, pointAt1, nextPart, pointAt2, radius, 0)
  File "/Users/enrico/Dropbox/dev/QAD-master/qad_utils.py", line 4079, in bridgeTheGapBetweenLines
    if distBetweenLine1Pt1AndPtInt > distBetweenLine1Pt2AndPtInt:
NameError: global name 'distBetweenLine1Pt1AndPtInt' is not defined

Versione Python:
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

Versione di QGIS:
2.10.1-Pisa Pisa, 

Percorso Python: ['/Users/enrico/.qgis2/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/enrico/.qgis2/python', u'/Users/enrico/Dropbox/dev', u'/Users/enrico/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/Applications/QGIS.app/Contents/MacOS/grass/etc/python', '/', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/PIL', u'/Users/enrico/.qgis2//python', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '/Users/enrico/Desktop/TEMP']

**Comment by geosim** [comment]
Thanks for testing. This bug should be fixed now. Sorry for the inconvenience.
