### ISSUE TITLE
Problem selecting features

### ISSUE THREAD

**Issue by PedroVenancio** [geosim/QAD#10]
The feature selected is always the first that was drawn after saving edits. 
That is, if you start editing a layer, draw a line, then draw a second line and try to select this second line, that is not possible because it is the first one that appears selected.
Ie, to be able to select successive lines, implies to save editions every time you introduce a new element, making it impossible to select previous features.

https://dl.dropboxusercontent.com/u/5772257/qgis/qad_problem_selecting_features.ogv 

Thanks @geosim !

**Comment by geosim** [comment]
Very strange !
   which qgis version are you using ? I use 2.8 on windows. I will try on xubuntu installing the same qgis version you are using...

**Comment by PedroVenancio** [comment]
Yes, it's very strange!
I'm using QGIS master, compiled by me on Xubuntu 14.04.

Thanks @geosim !

**Comment by geosim** [comment]
I have installed qgis pisa 2.10 on xubuntu 14.04 but i can't reproduce your problem. Can you send me a shape file and the qgis project file (.qgs) to reproduce the error ?

**Comment by PedroVenancio** [comment]
Hi @geosim 
I also can not reproduce this behavior anymore on QGIS 2.12 (self compiled).
So, this could be a local problem, or a problem solved meanwhile in the process of 2.12 development.
Thanks @geosim !
