### ISSUE TITLE
Please publish it on the standard repo 

### ISSUE THREAD

**Issue by gam17** [geosim/QAD#11]
Your plugin can be very useful for cad users.
Please publish it in the official repository.
If you don't, I can publish it for you (forking or duplicating your project).
Consider wider software reliability testing.

**Comment by geosim** [comment]
QAD is an open source plugin for QGIS. Of course you can do what you want: duplicate, fork, publish.
But you have to take the responsability of your actions.
There is a lot of logic similar to the most popular cad. For this reason we are waiting for a lawer council.
If you want to publish, do it under your own responsability, please.
