### ISSUE TITLE
Please use English as main language

### ISSUE THREAD

**Issue by pcav** [geosim/QAD#5]
both for the GUI and the documentation. Plugins can be translated using the standard method (i18n), as for other plugins.

**Comment by geosim** [comment]
At the moment there are 5754 word already translated in english. In the code we use italian but we provide qad_en.qm and qad_en.ts for english (i18n). If QGIS is in not in italian QAD searchs for the proper translation file, if it is not found it uses english version.

**Comment by geosim** [comment]
After 2 hard work weeks QAD uses english as main language. Added documentation too.

**Comment by luipir** [comment]
wonderful
@geosim can you share this news on qgis-developer list or I do it for you?

**Comment by geosim** [comment]
I can't...
